
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from base.base import Search

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\search")

search = Search()

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk(className='sw-search')

window.geometry("835x585")
window.configure(bg = "#000000")


canvas = Canvas(window, bg = "#000000", height = 585, width = 837, bd = 0, highlightthickness = 0, relief = "ridge")

canvas.place(x = 0, y = 0)
background = PhotoImage(file=relative_to_assets("background.png"))
image_1 = canvas.create_image(418.0, 292.0, image=background)

entry_1 = Entry(bd=0, bg="#000", fg="#fff", insertbackground='#fff', font='Helvetica 20')
entry_1.place(x=28.0, y=41.0, width=787.0, height=44.0)
entry_1.focus_set()

canvas.create_rectangle(23.0, 98.0, 280.0, 125.0, fill="#000",outline="")
canvas.create_rectangle(23.0, 135.0, 280.0, 162.0, fill="#000", outline="")

canvas.create_rectangle(292.0, 98.0, 550.0, 125.0, fill="#000", outline="")
canvas.create_rectangle(292.0, 135.0, 550.0, 162.0, fill="#000", outline="")

canvas.create_rectangle(562.0, 98.0, 820.0, 125.0, fill="#000", outline="")
canvas.create_rectangle(562.0, 135.0, 820.0, 162.0, fill="#000", outline="")

button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
button_1 = Button(image=button_image_1, borderwidth=0, highlightthickness=0, command=lambda: search.result(),
                  relief="flat")
button_1.place(x=600.0, y=511.0, width=220.0, height=56.0)

button_image_2 = PhotoImage(file=relative_to_assets("button_2.png"))
button_2 = Button(image=button_image_2,  borderwidth=0, highlightthickness=0, command=lambda: print("button_2 clicked"),
                  relief="flat")
button_2.place(x=367.0, y=512.0, width=220.0, height=56.0)


window.resizable(False, False)
window.mainloop()
