
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
from tkinter import Tk, Label, Button


class Translate():
    def __init__(self, person: dict = {}) -> None:
        self.person = person
    
    def get_screen(self):
        self.translate_window = Tk(className='sw-translate')
        self.translate_window.geometry("520x500")
        self.translate_window.configure(bg="#000")
        
        person = self.person.get('name', 'Yoda')
        description = self.person.get('description', 'mester Jedi')
        
        label_1 = Label(self.translate_window, bd=0, bg="#000",fg="#fff", font='Helvetica 20', text=person)
        label_1.place(x=28.0, y=41.0, width=461.0, height=44.0)
        label_2 = Label(self.translate_window,bd=0, bg="#000", fg="#fff", font='Helvetica 15', text=description)
        label_2.place(x=28.0, y=98.0, width=461.0, height=294.0)
        button_1 = Button(text='Voltar', borderwidth=0, highlightthickness=0, font='Helvetica 15', fg='#fff', 
                          command=lambda: self.translate_window.destroy(), relief="flat", background='#000',
                          )
        button_1.place(x=280.0, y=420.0, width=220.0, height=56.0 )        
        self.translate_window.resizable(False, False)
        self.translate_window.mainloop()

Translate(person={}).get_screen()